### ISSUE TITLE
[Fabric] BanMod bugs/errors

### ISSUE THREAD

**Issue by fyriandweller** [AMPZNetwork/BanMod#13]
# Commands that do **_NOT_** give the expected result 📝
- [ ] **/tempban**

### Expected result ✅
- [ ] **/tempban** ➡️ tempbans user and displays the ban in chat

### Actual result ❌
- [ ] **/tempban** ➡️ tempbans user but displays `Error:Player not found` in chat ⬇️

![image](https://github.com/user-attachments/assets/57b65b6a-5bcd-4d41-bf4d-72e6f3dec89f)

- [ ] upon issuing the same command ⬇️
```
/tempban notch 3min test
```
displays `User notch is already banned` ⬇️

![image](https://github.com/user-attachments/assets/a33bad75-e1bd-4050-bc93-277041c5220f)

# ⚠️ The following errors occur only in specific chunks (server spawn) ⚠️
### 🤔 perhaps some conflict with a mod/datapack
**_❗ upon further testing (~1 hour later), the client-console errors stopped occuring near server spawn area, for now ❗_**
<br><br/>
- [ ] **/cleanup everything**

### Expected result ✅
- [ ] **/cleanup everything** ➡️ cleans up everything _without_ errors

### Actual result ❌
- [ ] **/cleanup everything** ➡️ cleans up everything but gives client-console error ⬇️

```
javax.swing.text.BadLocationException: Invalid insert
at java.desktop/javax.swing.text.GapContent.insertString(Unknown Source)
at java.desktop/javax.swing.text.AbstractDocument.handleInsertString(Unknown Source)
at java.desktop/javax.swing.text.AbstractDocument.insertString(Unknown Source)
at com.atlauncher.gui.components.Console.write(Console.java:67)
at com.atlauncher.evnt.LogEvent.post(LogEvent.java:62)
at com.atlauncher.thread.LoggingThread.run(LoggingThread.java:46)
```

and then it spams the error ⬇️

```
[Render thread/FATAL] Error executing task on Client
```
constantly, (which freezes the client-console) only way to stop the client-console spam is to leave the server, upon joining the server again the client-console spam continues _but_ the client-console is responsive now

- [ ] **/tempban** & **/tempmute** & **/lookup** autocomplete

### Expected result ✅
- [ ] autocomplete shows all players online

### Actual result ❌
- [ ] autocomplete shows _only_ a few of the players online

# List of online players ⬇️
![image](https://github.com/user-attachments/assets/13993b75-cae5-4b82-8512-9f1d6e0ca8f9)

## Autocomplete partially working ⬇️
![image](https://github.com/user-attachments/assets/9d4c6022-b68f-46b8-b536-fc9b6f7c3e86)
![image](https://github.com/user-attachments/assets/4509409d-1bf2-43d9-afab-ba84406fa76c)
![image](https://github.com/user-attachments/assets/c7c2c995-89ee-48d9-b98f-e98225adc61f)

**Comment by fyriandweller** [comment]
dickfart
